export const catalogData = [
    {
        id: "1",
        title: "Oppenheimer",
        type: "movie",
        year: 2023,
        duration: "180 mins",
        rating: 8.9,
        age: "R",
        genre: "drama",
        genresList: ["Drama", "Biography", "History"],
        mood: "mindblowing",
        moodLabel: "Deep Thinking ",
        platforms: ["apple", "prime"],
        cast: "Cillian Murphy, Emily Blunt, Matt Damon",
        poster: "/Pic/Oppenheimer.webp",
        backdrop: "/bg pic/Oppenheimer.webp",
        overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
        trailerUrl: "https://www.youtube.com/embed/uYPbbksJxIg"
    },
    {
        id: "2",
        title: "Dune: Part Two",
        type: "movie",
        year: 2024,
        duration: "166 mins",
        rating: 8.7,
        age: "PG-13",
        genre: "scifi",
        genresList: ["Sci-Fi", "Action", "Adventure"],
        mood: "excited",
        moodLabel: "High adrenaline",
        platforms: ["hbo", "apple"],
        cast: "Timothée Chalamet, Zendaya, Rebecca Ferguson",
        poster: "/Pic/Dune Part Two.webp",
        backdrop: "/bg pic/dune-part-2.webp",
        overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
        trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w"
    },
    {
        id: "3",
        title: "Stranger Things",
        type: "series",
        year: 2022,
        duration: "4 Seasons",
        rating: 8.7,
        age: "TV-14",
        genre: "scifi",
        genresList: ["Sci-Fi", "Horror", "Mystery"],
        mood: "scared",
        moodLabel: "Spooky & Tense",
        platforms: ["netflix"],
        cast: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
        poster: "/Pic/Stranger Things.webp",
        backdrop: "/bg pic/Stranger Things.webp",
        overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        trailerUrl: "https://www.youtube.com/embed/b9EkMc79ZSU"
    },
    {
        id: "4",
        title: "Attack on Titan",
        type: "anime",
        year: 2023,
        duration: "4 Seasons",
        rating: 9.1,
        age: "TV-MA",
        genre: "animation",
        genresList: ["Anime", "Action", "Fantasy"],
        mood: "excited",
        moodLabel: "High adrenaline",
        platforms: ["hulu", "netflix"],
        cast: "Yuki Kaji, Yui Ishikawa, Marina Inoue",
        poster: "/Pic/attack.webp",
        backdrop: "/bg pic/Attack on Titan.webp",
        overview: "After his hometown is destroyed and his mother is killed, Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.",
        trailerUrl: "https://www.youtube.com/embed/M_OauHnAFc8"
    },
    {
        id: "5",
        title: "The Bear",
        type: "series",
        year: 2023,
        duration: "2 Seasons",
        rating: 8.6,
        age: "TV-MA",
        genre: "comedy",
        genresList: ["Drama", "Comedy"],
        mood: "excited",
        moodLabel: "Fast-Paced & Tense",
        platforms: ["hulu", "disney"],
        cast: "Jeremy Allen White, Ebon Moss-Bachrach, Ayo Edebiri",
        poster: "/Pic/The Bear.webp",
        backdrop: "/bg pic/The Bear.webp",
        overview: "A young fine-dining chef returns to Chicago to run his family's Italian beef sandwich shop after a tragedy.",
        trailerUrl: "https://www.youtube.com/embed/y-cE8C_vcfE"
    },
    {
        id: "6",
        title: "Our Planet",
        type: "doc",
        year: 2020,
        duration: "2 Seasons",
        rating: 9.3,
        age: "TV-PG",
        genre: "crime",
        genresList: ["Documentary", "Nature"],
        mood: "relaxed",
        moodLabel: "Chill & Cozy",
        platforms: ["netflix"],
        cast: "David Attenborough",
        poster: "/Pic/Our Planet.webp",
        backdrop: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1200&auto=format&fit=crop",
        overview: "Documentary series focusing on the breadth of diversity of habitats around the world, from the remote Arctic wilderness to South America.",
        trailerUrl: "https://www.youtube.com/embed/aETNYyrE69E"
    },
    {
        id: "7",
        title: "Severance",
        type: "series",
        year: 2022,
        duration: "Season 1",
        rating: 8.7,
        age: "TV-MA",
        genre: "scifi",
        genresList: ["Sci-Fi", "Mystery", "Thriller"],
        mood: "mindblowing",
        moodLabel: "Deep Thinking",
        platforms: ["apple"],
        cast: "Adam Scott, Zach Cherry, Patricia Arquette",
        poster: "/Pic/Severance.webp",
        backdrop: "/bg pic/Severance.webp",
        overview: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.",
        trailerUrl: "https://www.youtube.com/embed/xEQP4VVuyrY"
    },
    {
        id: "8",
        title: "Spirited Away",
        type: "anime",
        year: 2001,
        duration: "125 mins",
        rating: 8.6,
        age: "PG",
        genre: "animation",
        genresList: ["Anime", "Fantasy", "Family"],
        mood: "family",
        moodLabel: "Family Night & Magical",
        platforms: ["hbo", "netflix"],
        cast: "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
        poster: "/Pic/Spirited Away.webp",
        backdrop: "/bg pic/Spirited Away.webp",
        overview: "During her family's move to the suburbs, a 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
        trailerUrl: "https://www.youtube.com/embed/ByXuk9QqQkk"
    },
    {
        id: "9",
        title: "Spider-Man: Across the Spider-Verse",
        type: "movie",
        year: 2023,
        duration: "140 mins",
        rating: 8.7,
        age: "PG",
        genre: "animation",
        genresList: ["Animation", "Action", "Sci-Fi"],
        mood: "family",
        moodLabel: "High adrenaline",
        platforms: ["netflix", "prime"],
        cast: "Shameik Moore, Hailee Steinfeld, Oscar Isaac",
        poster: "/Pic/Spider-Man Across the Spider-Verse.webp",
        backdrop: "/bg pic/spider-man.webp",
        overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.",
        trailerUrl: "https://www.youtube.com/embed/cqGjhVJWtEg"
    },
    {
        id: "10",
        title: "The Dark Knight",
        type: "movie",
        year: 2008,
        duration: "152 mins",
        rating: 9.0,
        age: "PG-13",
        genre: "action",
        genresList: ["Action", "Crime", "Drama"],
        mood: "excited",
        moodLabel: "High adrenaline",
        platforms: ["hbo", "prime"],
        cast: "Christian Bale, Heath Ledger, Aaron Eckhart",
        poster: "/Pic/The Dark Knight.webp",
        backdrop: "/bg pic/The Dark Knight.webp",
        overview: "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/EXeTwQWrcwY"
    },
    {
        id: "11",
        title: "Succession",
        type: "series",
        year: 2023,
        duration: "4 Seasons",
        rating: 8.9,
        age: "TV-MA",
        genre: "drama",
        genresList: ["Drama", "Business"],
        mood: "mindblowing",
        moodLabel: "Deep Thinking ",
        platforms: ["hbo"],
        cast: "Brian Cox, Jeremy Strong, Sarah Snook",
        poster: "/Pic/Succession.webp",
        backdrop: "/bg pic/Succession.webp",
        overview: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/OzYxJV_rmE8"
    },
    {
        id: "12",
        title: "Demon Slayer: Kimetsu no Yaiba",
        type: "anime",
        year: 2024,
        duration: "4 Seasons",
        rating: 8.6,
        age: "TV-14",
        genre: "animation",
        genresList: ["Anime", "Action", "Fantasy"],
        mood: "excited",
        moodLabel: "High adrenaline",
        platforms: ["netflix", "hulu"],
        cast: "Natsuki Hanae, Akari Kito, Hiro Shimono",
        poster: "/Pic/Demon Slayer Kimetsu no Yaiba.webp",
        backdrop: "/bg pic/Demon Slayer Kimetsu no Yaiba.webp",
        overview: "A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon herself.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/VQGCKyuzIM4"
    },
    {
        id: "13",
        title: "Inception",
        type: "movie",
        year: 2010,
        duration: "148 mins",
        rating: 8.8,
        age: "PG-13",
        genre: "scifi",
        genresList: ["Sci-Fi", "Action", "Thriller"],
        mood: "mindblowing",
        moodLabel: "Mind-Bending & Epic",
        platforms: ["prime", "apple"],
        cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        poster: "/Pic/Inception.webp",
        backdrop: "/bg pic/Inception.webp",
        overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/YoHD9XEInc0"
    },
    {
        id: "14",
        title: "Superbad",
        type: "movie",
        year: 2007,
        duration: "113 mins",
        rating: 7.6,
        age: "R",
        genre: "comedy",
        genresList: ["Comedy", "Teen"],
        mood: "laugh",
        moodLabel: "need a laugh",
        platforms: ["netflix"],
        cast: "Jonah Hill, Michael Cera, Christopher Mintz-Plasse",
        poster: "/Pic/Superbad.webp",
        backdrop: "/bg pic/Superbad.webp",
        overview: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to host a booze-soaked party goes awry.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/4eaZ_48ZYog"
    },
    {
        id: "15",
        title: "A Quiet Place",
        type: "movie",
        year: 2018,
        duration: "90 mins",
        rating: 7.5,
        age: "PG-13",
        genre: "horror",
        genresList: ["Horror", "Sci-Fi", "Drama"],
        mood: "scared",
        moodLabel: "Spooky & Tense",
        platforms: ["paramount", "prime"],
        cast: "Emily Blunt, John Krasinski, Millicent Simmonds",
        poster: "/Pic/A Quiet Place.webp",
        backdrop: "/bg pic/A Quiet Place.webp",
        overview: "A family must live in silence while hiding from creatures that hunt by sound in a post-apocalyptic world.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/WR7cc5t7niU"
    },
    {
        id: "16",
        title: "La La Land",
        type: "movie",
        year: 2016,
        duration: "128 mins",
        rating: 8.0,
        age: "PG-13",
        genre: "romance",
        genresList: ["Romance", "Drama", "Music"],
        mood: "relaxed",
        moodLabel: "Heartfelt & Cozy",
        platforms: ["prime", "apple"],
        cast: "Ryan Gosling, Emma Stone, Rosemarie DeWitt",
        poster: "/Pic/La La Land.webp",
        backdrop: "/bg pic/La La Land.webp",
        overview: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/0pdqf4P9MB8"
    },
    {
        id: "17",
        title: "Breaking Bad",
        type: "series",
        year: 2013,
        duration: "5 Seasons",
        rating: 9.5,
        age: "TV-MA",
        genre: "crime",
        genresList: ["Crime", "Drama", "Thriller"],
        mood: "mindblowing",
        moodLabel: "Deep Thinking & Intense",
        platforms: ["netflix"],
        cast: "Bryan Cranston, Aaron Paul, Anna Gunn",
        poster: "/Pic/Breaking Bad.webp",
        backdrop: "/bg pic/Breaking Bad.webp",
        overview: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student to secure his family's future.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/HhesaQXLuRY"
    },
    {
        id: "18",
        title: "F1: Drive to Survive",
        type: "doc",
        year: 2024,
        duration: "6 Seasons",
        rating: 8.5,
        age: "TV-MA",
        genre: "action",
        genresList: ["Documentary", "Sports"],
        mood: "excited",
        moodLabel: "High adrenaline",
        platforms: ["netflix"],
        cast: "Formula 1 Drivers & Team Principals",
        poster: "/Pic/F1 Drive to Survive.webp",
        backdrop: "/bg pic/F1 Drive to Survive.webp",
        overview: "Drivers, managers and team owners live life in the fast lane — both on and off the track — during each cutthroat season of Formula 1 racing.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/wtJPe1ksS6E"
    },
    {
        id: "19",
        title: "Jujutsu Kaisen",
        type: "anime",
        year: 2023,
        duration: "2 Seasons",
        rating: 8.6,
        age: "TV-MA",
        genre: "animation",
        genresList: ["Anime", "Action", "Supernatural"],
        mood: "excited",
        moodLabel: "High adrenaline",
        platforms: ["netflix", "hulu"],
        cast: "Junya Enoki, Yuma Uchida, Asami Seto",
        poster: "/Pic/Jujutsu Kaisen.webp",
        backdrop: "/bg pic/Jujutsu Kaisen.webp",
        overview: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/pkNEKEo5DiQ"
    },
    {
        id: "20",
        title: "The Last Dance",
        type: "doc",
        year: 2020,
        duration: "1 Season",
        rating: 9.1,
        age: "TV-MA",
        genre: "drama",
        genresList: ["Documentary", "Sports", "Biography"],
        mood: "mindblowing",
        moodLabel: "Deep Thinking ",
        platforms: ["netflix"],
        cast: "Michael Jordan, Scottie Pippen, Phil Jackson",
        poster: "/Pic/The Last Dance.webp",
        backdrop: "https://images.unsplash.com/photo-1519861531473-9200262188bf?q=80&w=1200&auto=format&fit=crop",
        overview: "Charted alongside the 1997-98 Chicago Bulls season, this docuseries chronicles the rise of Michael Jordan and the 1990s NBA dynasty.",
        trailerUrl: "https://www.youtube-nocookie.com/embed/Peh9Yqf1GXc"
    }
];
